name: picklebay-website-dev CI

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: dev-runner

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: |
          touch .env
          echo "$${{ secrets.DEV_ENV_FILE }}" > .env
      - run: npm run build
      - run: pm2 restart picklebay-website-dev
      - run: pm2 flush picklebay-website-dev
